# Generated by Django 3.0.8 on 2020-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('turn_id', models.IntegerField(null=True)),
                ('players', models.IntegerField()),
                ('players_want_play', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=20)),
                ('play_on', models.CharField(max_length=100, null=True)),
                ('health', models.IntegerField(null=True)),
                ('canon_orientation', models.FloatField(null=True)),
                ('puissance', models.FloatField(null=True)),
                ('shoot', models.IntegerField(null=True)),
                ('pos_x', models.FloatField(null=True)),
                ('pos_y', models.FloatField(null=True)),
                ('want_to_play', models.IntegerField()),
            ],
        ),
    ]
