# Generated by Django 3.0.8 on 2020-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='want_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
