# Generated by Django 3.0.8 on 2020-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200712_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='canon_orientation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pos_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pos_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='puissance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shoot',
            field=models.IntegerField(null=True),
        ),
    ]
