# Generated by Django 3.0.8 on 2020-07-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200721_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='end_of_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='play_on',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoot',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
